services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  server:
    build: ./server
    ports:
      - "8080:8080"
    env_file:
      - ./server/.env
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build: ./front
    ports:
      - "3000:80"
    depends_on:
      - server
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
